"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type Conversation={id:string;title:string;updatedAt:number};type Message={id?:string;role:"user"|"assistant";content:string};type Props={user:{name:string;email:string}};
export default function ChatApp({user}:Props){
 const [conversations,setConversations]=useState<Conversation[]>([]),[active,setActive]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(false),[settings,setSettings]=useState(false),[theme,setTheme]=useState("light"),[tone,setTone]=useState("warm"),[error,setError]=useState("");const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{Promise.all([fetch("/api/conversations").then(r=>r.json()),fetch("/api/profile").then(r=>r.json())]).then(([a,b])=>{setConversations(a.conversations??[]);if(b.profile){setTheme(b.profile.theme);setTone(b.profile.tone)}})},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme==="system"?"":theme},[theme]);useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,loading]);
 async function open(id:string){setActive(id);setSidebar(false);setError("");const data=await fetch(`/api/conversations/${id}`).then(r=>r.json());setMessages(data.messages??[])}
 async function create(){const data=await fetch("/api/conversations",{method:"POST"}).then(r=>r.json());if(data.conversation){setConversations(c=>[data.conversation,...c]);setActive(data.conversation.id);setMessages([]);setSidebar(false)}}
 async function remove(id:string){if(!confirm("¿Eliminar esta conversación de forma permanente?"))return;await fetch(`/api/conversations/${id}`,{method:"DELETE"});setConversations(c=>c.filter(x=>x.id!==id));if(active===id){setActive(null);setMessages([])}}
 async function send(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||loading)return;let id=active;if(!id){const d=await fetch("/api/conversations",{method:"POST"}).then(r=>r.json());id=d.conversation?.id;if(!id)return;setActive(id);setConversations(c=>[d.conversation,...c])}setInput("");setError("");setMessages(m=>[...m,{role:"user",content:text}]);setLoading(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id,message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(m=>[...m,{role:"assistant",content:d.message.content}]);setConversations(c=>c.map(x=>x.id===id?{...x,title:d.title,updatedAt:Date.now()}:x).sort((a,b)=>b.updatedAt-a.updatedAt))}catch(e){setError(e instanceof Error?e.message:"No se pudo enviar.")}finally{setLoading(false)}}
 async function saveSetting(kind:"theme"|"tone",value:string){if(kind==="theme")setTheme(value);else setTone(value);await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[kind]:value})})}
 return <div className="chat-shell"><aside className={sidebar?"sidebar open":"sidebar"}><div className="side-brand"><span className="logo-mark">n</span><b>nora</b><button onClick={()=>setSidebar(false)} aria-label="Cerrar menú">×</button></div><button className="new-chat" onClick={create}>＋ Nueva conversación</button><div className="history"><small>CONVERSACIONES</small>{conversations.length===0?<p className="empty-history">Aún no hay conversaciones.</p>:conversations.map(c=><div className={active===c.id?"history-item active":"history-item"} key={c.id}><button onClick={()=>open(c.id)}>{c.title}</button><button className="delete-chat" onClick={()=>remove(c.id)} aria-label={`Eliminar ${c.title}`}>×</button></div>)}</div><div className="account"><button onClick={()=>setSettings(true)}><span>{user.name.charAt(0).toUpperCase()}</span><div><b>{user.name}</b><small>Configuración</small></div><i>•••</i></button></div></aside>
 <main className="chat-main"><header className="chat-top"><button className="mobile-menu" onClick={()=>setSidebar(true)}>☰</button><span><b>Nora</b><small>Apoyo emocional con IA</small></span><button className="profile-button" onClick={()=>setSettings(true)}>{user.name.charAt(0).toUpperCase()}</button></header><section className="conversation">{messages.length===0?<div className="welcome"><span className="logo-mark large">n</span><h1>Hola, {user.name.split(" ")[0]}.</h1><p>Este es tu espacio. ¿Qué tienes en mente hoy?</p><div className="suggestions">{["Necesito desahogarme","Quiero calmar mi ansiedad","Ayúdame a ordenar mis ideas","Solo quiero conversar"].map(x=><button key={x} onClick={()=>setInput(x)}>{x}<span>→</span></button>)}</div></div>:<div className="message-list">{messages.map((m,i)=><article className={`app-message ${m.role}`} key={m.id??i}>{m.role==="assistant"&&<span className="logo-mark small">n</span>}<div><b>{m.role==="assistant"?"Nora":"Tú"}</b><p>{m.content}</p></div></article>)}{loading&&<article className="app-message assistant"><span className="logo-mark small">n</span><div><b>Nora</b><p className="dots">Pensando con cuidado…</p></div></article>}<div ref={end}/></div>} </section><div className="composer-wrap">{error&&<div className="app-error">{error}</div>}<form className="composer" onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} maxLength={4000} placeholder="Escribe un mensaje a Nora…" rows={1}/><button disabled={!input.trim()||loading} aria-label="Enviar">↑</button></form><small>Nora puede cometer errores y no reemplaza la atención profesional. En una emergencia, llama a los servicios locales.</small></div></main>
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="settings-modal" onClick={e=>e.stopPropagation()}><header><div><h2>Configuración</h2><p>Personaliza tu experiencia con Nora.</p></div><button onClick={()=>setSettings(false)}>×</button></header><div className="profile-card"><span>{user.name.charAt(0).toUpperCase()}</span><div><b>{user.name}</b><small>{user.email}</small></div></div><label>Tema<select value={theme} onChange={e=>saveSetting("theme",e.target.value)}><option value="light">Claro</option><option value="dark">Oscuro</option><option value="system">Sistema</option></select></label><label>Personalidad de Nora<select value={tone} onChange={e=>saveSetting("tone",e.target.value)}><option value="warm">Cálida</option><option value="serious">Serena y directa</option><option value="gentle">Muy tierna</option></select></label><a className="signout" href="/signout-with-chatgpt?return_to=/">Cerrar sesión</a></section></div>}
 </div>
}
