"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type Conversation={id:string;title:string;updatedAt:number};type Message={id?:string;role:"user"|"assistant";content:string;important?:boolean};type Props={user:{name:string;email:string}};
export default function ChatApp({user}:Props){
 const [conversations,setConversations]=useState<Conversation[]>([]),[active,setActive]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(false),[settings,setSettings]=useState(false),[theme,setTheme]=useState("light"),[tone,setTone]=useState("warm"),[fontSize,setFontSize]=useState("medium"),[reduceMotion,setReduceMotion]=useState(false),[error,setError]=useState("");const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{Promise.all([fetch("/api/conversations").then(r=>r.json()),fetch("/api/profile").then(r=>r.json())]).then(([a,b])=>{setConversations(a.conversations??[]);if(b.profile){setTheme(b.profile.theme);setTone(b.profile.tone);setFontSize(b.profile.fontSize??"medium");setReduceMotion(Boolean(b.profile.reduceMotion))}})},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme==="system"?"":theme;document.documentElement.dataset.font=fontSize;document.documentElement.dataset.motion=reduceMotion?"reduced":"full"},[theme,fontSize,reduceMotion]);useEffect(()=>{end.current?.scrollIntoView({behavior:reduceMotion?"auto":"smooth"})},[messages,loading,reduceMotion]);
 async function open(id:string){setActive(id);setSidebar(false);setError("");const data=await fetch(`/api/conversations/${id}`).then(r=>r.json());setMessages(data.messages??[])}
 async function create(){const data=await fetch("/api/conversations",{method:"POST"}).then(r=>r.json());if(data.conversation){setConversations(c=>[data.conversation,...c]);setActive(data.conversation.id);setMessages([]);setSidebar(false)}}
 async function remove(id:string){if(!confirm("¿Eliminar esta conversación de forma permanente?"))return;await fetch(`/api/conversations/${id}`,{method:"DELETE"});setConversations(c=>c.filter(x=>x.id!==id));if(active===id){setActive(null);setMessages([])}}
 async function send(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||loading)return;let id=active;if(!id){const d=await fetch("/api/conversations",{method:"POST"}).then(r=>r.json());id=d.conversation?.id;if(!id)return;setActive(id);setConversations(c=>[d.conversation,...c])}const tempId=`temp-${Date.now()}`;setInput("");setError("");setMessages(m=>[...m,{id:tempId,role:"user",content:text,important:false}]);setLoading(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id,message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(m=>[...m.map(x=>x.id===tempId?d.userMessage:x),d.message]);setConversations(c=>c.map(x=>x.id===id?{...x,title:d.title,updatedAt:Date.now()}:x).sort((a,b)=>b.updatedAt-a.updatedAt))}catch(e){setError(e instanceof Error?e.message:"No se pudo enviar.")}finally{setLoading(false)}}
 async function saveSetting(kind:"theme"|"tone"|"fontSize"|"reduceMotion",value:string|boolean){if(kind==="theme")setTheme(String(value));else if(kind==="tone")setTone(String(value));else if(kind==="fontSize")setFontSize(String(value));else setReduceMotion(Boolean(value));await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[kind]:value})})}
 async function toggleImportant(message:Message){if(!message.id||message.id.startsWith("temp-"))return;const important=!message.important;setMessages(list=>list.map(item=>item.id===message.id?{...item,important}:item));const response=await fetch(`/api/messages/${message.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({important})});if(!response.ok)setMessages(list=>list.map(item=>item.id===message.id?{...item,important:!important}:item))}
 return <div className="chat-shell"><aside className={sidebar?"sidebar open":"sidebar"}><div className="side-brand"><span className="logo-mark">n</span><b>nora</b><button onClick={()=>setSidebar(false)} aria-label="Cerrar menú">×</button></div><button className="new-chat" onClick={create}>＋ Nueva conversación</button><div className="history"><small>CONVERSACIONES</small>{conversations.length===0?<p className="empty-history">Aún no hay conversaciones.</p>:conversations.map(c=><div className={active===c.id?"history-item active":"history-item"} key={c.id}><button onClick={()=>open(c.id)}>{c.title}</button><button className="delete-chat" onClick={()=>remove(c.id)} aria-label={`Eliminar ${c.title}`}>×</button></div>)}</div><div className="account"><button onClick={()=>setSettings(true)}><span>{user.name.charAt(0).toUpperCase()}</span><div><b>{user.name}</b><small>Configuración</small></div><i>•••</i></button></div></aside>
 <main className="chat-main"><header className="chat-top"><button className="mobile-menu" onClick={()=>setSidebar(true)}>☰</button><span><b>Nora</b><small>Aquí para escucharte</small></span><button className="profile-button" onClick={()=>setSettings(true)}>{user.name.charAt(0).toUpperCase()}</button></header><section className="conversation">{messages.length===0?<div className="welcome"><span className="logo-mark large">n</span><h1>Hola, {user.name.split(" ")[0]}.</h1><p>Estoy aquí contigo. Puedes contarme lo que necesites, a tu ritmo.</p><div className="suggestions">{["Necesito desahogarme","Hoy no ha sido un buen día","Tengo algo en la cabeza","Solo quiero conversar"].map(x=><button key={x} onClick={()=>setInput(x)}>{x}<span>→</span></button>)}</div></div>:<div className="message-list">{messages.map((m,i)=><article className={`app-message ${m.role}`} key={m.id??i}>{m.role==="assistant"&&<span className="logo-mark small">n</span>}<div><div className="message-head"><b>{m.role==="assistant"?"Nora":"Tú"}</b><button className={m.important?"memory-button saved":"memory-button"} onClick={()=>toggleImportant(m)} title={m.important?"Quitar de momentos importantes":"Guardar como importante"}>{m.important?"★":"☆"}</button></div><p>{m.content}</p></div></article>)}{loading&&<article className="app-message assistant"><span className="logo-mark small">n</span><div><b>Nora</b><p className="dots">Estoy aquí, pensando en lo que me contaste…</p></div></article>}<div ref={end}/></div>} </section><div className="composer-wrap">{error&&<div className="app-error">{error}</div>}<form className="composer" onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} maxLength={4000} placeholder="Cuéntame lo que estás sintiendo…" rows={1}/><button disabled={!input.trim()||loading} aria-label="Enviar">↑</button></form><small>Usa ☆ para guardar algo importante. Nora acompaña, pero no reemplaza atención profesional.</small></div></main>
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="settings-modal" onClick={e=>e.stopPropagation()}><header><div><h2>Tu espacio</h2><p>Haz que Nora se sienta cómoda para ti.</p></div><button onClick={()=>setSettings(false)}>×</button></header><div className="profile-card"><span>{user.name.charAt(0).toUpperCase()}</span><div><b>{user.name}</b><small>{user.email}</small></div></div><label>Apariencia<select value={theme} onChange={e=>saveSetting("theme",e.target.value)}><option value="light">Blanco</option><option value="dark">Negro</option><option value="system">Usar la del dispositivo</option></select></label><label>Cómo quieres que te acompañe<select value={tone} onChange={e=>saveSetting("tone",e.target.value)}><option value="warm">Cercana y natural</option><option value="reflective">Reflexiva y pausada</option><option value="gentle">Especialmente tierna</option></select></label><label>Tamaño del texto<select value={fontSize} onChange={e=>saveSetting("fontSize",e.target.value)}><option value="small">Pequeño</option><option value="medium">Mediano</option><option value="large">Grande</option></select></label><label className="toggle-label"><span><b>Reducir animaciones</b><small>Una experiencia más tranquila</small></span><input type="checkbox" checked={reduceMotion} onChange={e=>saveSetting("reduceMotion",e.target.checked)}/></label><div className="memory-tip"><span>★</span><p><b>Momentos importantes</b>Pulsa la estrella junto a cualquier mensaje para conservarlo como importante.</p></div><a className="signout" href="/api/auth/logout?returnTo=/">Cerrar sesión</a></section></div>}
 </div>
}
