const features = [
  { icon: "◌", title: "Conversaciones que continúan", text: "Vuelve a tus chats y retoma el hilo sin tener que explicar todo desde el principio." },
  { icon: "♡", title: "Escucha antes de aconsejar", text: "Nora busca comprender primero y pregunta antes de proponerte una herramienta." },
  { icon: "◇", title: "Memoria bajo tu control", text: "Decide qué momentos o datos recordar. Puedes revisarlos, apagarlos o borrarlos." },
  { icon: "◫", title: "Tu espacio, a tu manera", text: "Ajusta el tono, la profundidad, el tamaño del texto, el contraste y las animaciones." },
  { icon: "⇩", title: "Tus datos son portables", text: "Exporta una conversación o descarga una copia completa de tu información." },
  { icon: "⌁", title: "Diseñada para cualquier pantalla", text: "Una experiencia clara y accesible tanto en celular como en computadora." },
];
const faqs = [
  ["¿Nora es una psicóloga?", "No. Nora es una inteligencia artificial de acompañamiento emocional. Puede escuchar, ayudarte a poner palabras a lo que sientes y ofrecer ideas de autocuidado, pero no diagnostica ni reemplaza terapia o atención médica."],
  ["¿Qué recuerda Nora?", "El contexto reciente de la conversación, los mensajes que marques como importantes y los recuerdos que añadas voluntariamente. Puedes desactivar la memoria o eliminar cualquier recuerdo."],
  ["¿Quién puede leer mis conversaciones?", "El historial está asociado a tu cuenta. Para producir una respuesta, el mensaje y el contexto necesario se procesan mediante el proveedor de IA. Evita compartir contraseñas, documentos, domicilios u otros datos que no quieras procesar."],
  ["¿Qué hago si estoy en peligro?", "Nora no es un servicio de emergencia. Si existe peligro inmediato o podrías hacerte daño, contacta ahora los servicios de emergencia de tu país y busca a una persona de confianza que pueda permanecer contigo."],
];

export default function Home() {
  return <main>
    <nav className="nav launch-nav"><a className="brand" href="#inicio"><span className="logo-mark small">n</span><span>nora</span></a><div className="nav-links"><a href="#que-es">Qué es</a><a href="#como-funciona">Cómo funciona</a><a href="#creador">Creador</a><a href="#seguridad">Seguridad</a><a className="nav-cta" href="/chat">Entrar <span>→</span></a></div></nav>
    <section className="launch-hero" id="inicio"><div className="launch-badge">PROYECTO POR EL MES DE LA PREVENCIÓN DEL SUICIDIO</div><div className="hero-logo"><span className="logo-mark hero-mark">n</span><h1>nora</h1></div><p className="hero-tagline">Un lugar para decir lo que a veces cuesta poner en palabras.</p><p className="hero-support">Acompañamiento emocional con inteligencia artificial, a tu ritmo y sin juicios.</p><a className="enter-button" href="/chat">Entrar a Nora <span>→</span></a><small>Acceso con Google o correo · Configuración y memoria privadas</small><div className="hero-orbit one"/><div className="hero-orbit two"/></section>

    <section className="manifesto" id="que-es"><div className="section-tag">QUÉ ES NORA</div><h2>Una conversación puede<br/><em>abrir un poco de espacio.</em></h2><p>Nora es una compañera digital creada para ofrecer una primera escucha cuando necesitas desahogarte, ordenar una emoción o sentirte acompañado. No busca darte una respuesta perfecta: busca escucharte con atención, hacer preguntas útiles y avanzar contigo poco a poco.</p><div className="purpose-note"><span>♡</span><p><b>Una herramienta de apoyo, no un reemplazo</b>Nora no diagnostica ni sustituye a profesionales de salud mental o servicios de emergencia. Pedir ayuda humana y profesional también es una forma de cuidarte.</p></div></section>

    <section className="real-quote"><span>“</span><blockquote>Hacer nuestra historia propia y amarnos a lo largo de ese proceso es lo más valiente que haremos.</blockquote><p>— Brené Brown · <em>Los dones de la imperfección</em> · Traducción al español</p></section>

    <section className="audience-section"><div><div className="section-tag light">PARA MOMENTOS REALES</div><h2>No necesitas estar “muy mal” para querer hablar.</h2></div><div className="audience-grid"><article><span>01</span><h3>Cuando algo te pesa</h3><p>Conflictos familiares, escolares, de pareja, amistades o decisiones difíciles.</p></article><article><span>02</span><h3>Cuando no sabes nombrarlo</h3><p>Explora lo que sientes sin la presión de tener las palabras correctas.</p></article><article><span>03</span><h3>Cuando quieres conocerte</h3><p>Reconoce patrones, necesidades, límites y pequeñas formas de cuidarte.</p></article><article><span>04</span><h3>Cuando solo quieres compañía</h3><p>También puedes conversar sin convertir cada momento en un problema que resolver.</p></article></div></section>

    <section className="professional-features"><div className="section-tag">PENSADA PARA CUIDAR LA EXPERIENCIA</div><div className="pro-grid expanded">{features.map((feature, index) => <article key={feature.title}><small>{String(index + 1).padStart(2, "0")}</small><span>{feature.icon}</span><h3>{feature.title}</h3><p>{feature.text}</p></article>)}</div></section>

    <section className="how-section" id="como-funciona"><div className="how-heading"><div className="section-tag">CÓMO FUNCIONA</div><h2>Empieza donde estés.</h2><p>No hay formularios clínicos ni una manera correcta de hablar.</p></div><ol><li><span>1</span><div><h3>Entra a tu espacio</h3><p>Accede con Google o crea una cuenta con correo. Tus chats quedan separados por usuario.</p></div></li><li><span>2</span><div><h3>Cuéntalo a tu manera</h3><p>Escribe una frase, una historia completa o simplemente “no sé cómo empezar”.</p></div></li><li><span>3</span><div><h3>Conserva solo lo importante</h3><p>Marca momentos con una estrella o escribe “recuerda que…”. Tú puedes revisar y borrar todo.</p></div></li></ol></section>

    <section className="creator" id="creador"><div className="creator-art"><span className="logo-mark creator-mark">n</span><div className="creator-ring"/></div><div><div className="section-tag">QUIÉN CREÓ NORA</div><h2>Una idea de<br/><em>Gerard Ramces<br/>Bollard Gonzalez.</em></h2><p>Nora nace en 2026 como un proyecto por el Mes de la Prevención del Suicidio, con la intención de acercar una primera escucha a quienes sienten que no tienen con quién hablar y recordar que pedir ayuda nunca debería dar vergüenza.</p><p>El proyecto combina tecnología, diseño emocional y el deseo de crear una experiencia accesible desde cualquier dispositivo.</p><a className="creator-cta" href="/chat">Conocer a Nora <span>→</span></a></div></section>

    <section className="honest-section"><div className="section-tag">LO QUE NORA HACE — Y LO QUE NO</div><h2>Apoyo honesto, con límites claros.</h2><div className="honest-grid"><article><span>✓</span><h3>Sí puede</h3><p>Escuchar, ayudarte a identificar emociones, ordenar ideas, preparar una conversación difícil y compartir ejercicios sencillos cuando tú quieras.</p></article><article><span>×</span><h3>No puede</h3><p>Diagnosticar, recetar, garantizar resultados, actuar fuera del chat, contactar emergencias por ti ni reemplazar una relación terapéutica.</p></article><article><span>!</span><h3>Puede equivocarse</h3><p>La IA puede interpretar mal algo o dar una respuesta poco útil. Puedes corregirla, cambiar su estilo o buscar apoyo humano cuando lo necesites.</p></article></div></section>

    <section className="safe-section" id="seguridad"><div><div className="section-tag light">PRIVACIDAD Y SEGURIDAD</div><h2>Tu historia te pertenece.</h2><p>La memoria es visible y opcional. Tu perfil, chats y preferencias se guardan para darte continuidad, y puedes descargar o eliminar tus datos en cualquier momento.</p></div><ul><li><span>✓</span> Historial separado y protegido por cuenta</li><li><span>✓</span> Recuerdos visibles, editables y opcionales</li><li><span>✓</span> Exportación de chats y datos personales</li><li><span>✓</span> Eliminación permanente desde configuración</li><li><span>✓</span> Claves de servicios protegidas en el servidor</li></ul></section>

    <section className="faq-section"><div className="section-tag">PREGUNTAS IMPORTANTES</div><h2>Antes de comenzar.</h2><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>＋</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="crisis-note"><span>!</span><div><h2>Si existe peligro inmediato</h2><p>No esperes una respuesta de una aplicación. Contacta los servicios de emergencia de tu país, acércate a una persona de confianza y procura no quedarte solo. Si puedes, aléjate de cualquier objeto o sustancia con la que pudieras hacerte daño.</p></div></section>
    <section className="final-cta"><span className="logo-mark large">n</span><h2>Cuando quieras hablar,<br/>Nora está aquí.</h2><p>Empieza con una palabra. No necesitas saber exactamente qué decir.</p><a className="enter-button" href="/chat">Iniciar sesión y entrar <span>→</span></a></section>
    <footer><a className="brand footer-brand" href="#inicio"><span className="logo-mark small">n</span><span>nora</span></a><p>Creada con cuidado por Gerard Ramces Bollard Gonzalez.</p><small>© 2026 Nora · Acompañamiento emocional con IA, no atención médica ni servicio de emergencia.</small></footer>
  </main>;
}
