const features=[{icon:"◌",title:"Conversaciones que continúan",text:"Tus chats se guardan de forma privada para que puedas volver a ellos cuando quieras."},{icon:"♡",title:"Escucha con empatía",text:"Respuestas cálidas inspiradas en escucha activa y autorregulación emocional."},{icon:"✦",title:"Una Nora para ti",text:"Elige tema claro u oscuro y el tono con el que prefieres ser acompañado."}];
export default function Home(){return <main><nav className="nav"><a className="brand" href="#inicio"><span className="logo-mark small">n</span><span>nora</span></a><div className="nav-links"><a href="#proposito">Propósito</a><a href="#creador">Quién la creó</a><a href="#seguridad">Seguridad</a><a className="nav-cta" href="/chat">Entrar <span>→</span></a></div></nav>
<section className="launch-hero" id="inicio"><div className="launch-badge">MES DE LA PREVENCIÓN DEL SUICIDIO · SEPTIEMBRE</div><div className="hero-logo"><span className="logo-mark hero-mark">n</span><h1>nora</h1></div><p className="hero-tagline">Un espacio seguro para decir lo que a veces cuesta poner en palabras.</p><a className="enter-button" href="/chat">Entrar a Nora <span>→</span></a><small>Se requiere iniciar sesión · Tus conversaciones son privadas</small><div className="hero-orbit one"/><div className="hero-orbit two"/></section>
<section className="manifesto" id="proposito"><div className="section-tag">NUESTRO PROPÓSITO</div><h2>No tienes que atravesarlo<br/><em>en silencio.</em></h2><p>Nora es una inteligencia artificial de acompañamiento emocional. Un lugar accesible, humano y sin juicios donde puedes expresarte, comprender lo que sientes y encontrar un poco de claridad.</p><div className="purpose-note"><span>♡</span><p><b>Importante</b>Nora acompaña, pero no reemplaza a un psicólogo ni a los servicios de emergencia. Pedir ayuda profesional también es cuidarte.</p></div></section>
<section className="professional-features"><div className="section-tag">UNA EXPERIENCIA PENSADA PARA CUIDARTE</div><div className="pro-grid">{features.map((f,i)=><article key={f.title}><small>0{i+1}</small><span>{f.icon}</span><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
<section className="creator" id="creador"><div className="creator-art"><span className="logo-mark creator-mark">n</span><div className="creator-ring"/></div><div><div className="section-tag">QUIÉN CREÓ NORA</div><h2>Una idea de<br/><em>Gerard Ramces<br/>Bollard Gonzalez.</em></h2><p>Nora nace como un proyecto por el Mes de la Prevención del Suicidio, con la intención de acercar una primera escucha a quienes sienten que no tienen con quién hablar.</p><blockquote>“La tecnología también puede ser un puente hacia la empatía, la conversación y la búsqueda de ayuda.”</blockquote><small>— GERARD RAMCES BOLLARD GONZALEZ · 2026</small></div></section>
<section className="safe-section" id="seguridad"><div><div className="section-tag light">PRIVACIDAD Y SEGURIDAD</div><h2>Tu historia te pertenece.</h2><p>El acceso protege tu historial. Solo tú puedes consultar y eliminar tus conversaciones, y tus preferencias se mantienen en tu cuenta.</p></div><ul><li><span>✓</span> Historial privado por usuario</li><li><span>✓</span> Conversaciones que puedes borrar</li><li><span>✓</span> Configuración personal persistente</li><li><span>✓</span> Clave de IA protegida en el servidor</li></ul></section>
<section className="final-cta"><span className="logo-mark large">n</span><h2>Cuando quieras hablar,<br/>Nora está aquí.</h2><p>Empieza con una palabra. No tienes que saber exactamente qué decir.</p><a className="enter-button" href="/chat">Iniciar sesión y entrar <span>→</span></a></section>
<footer><a className="brand footer-brand" href="#inicio"><span className="logo-mark small">n</span><span>nora</span></a><p>Creada con cuidado por Gerard Ramces Bollard Gonzalez.</p><small>© 2026 Nora · Apoyo emocional, no atención médica.</small></footer></main>}
